name: Setup CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create non-root user
        run: |
          sudo useradd -m testuser
          echo "testuser ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/testuser

      - name: Step-1 install package
        run: |
          sudo -u testuser bash <<'EOF'
            set -euxo pipefail

            # 1) 必要なパッケージのインストール
            sudo apt update -y && sudo apt install -y git curl vim

      - name: Step-2 checkout dotfiles
        run: |
          sudo -u testuser bash <<'EOF'
            set -euxo pipefail
            # CI限定
            rm -f $HOME/.bashrc

            # 2) dotfiles の bare-repo 方式での管理
            git clone --bare https://github.com/mtakagishi/dotfiles.git $HOME/.dotfiles
            git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout
            git --git-dir=$HOME/.dotfiles --work-tree=$HOME \
              config --local status.showUntrackedFiles no

      - name: Step-3 install.sh
        run: |
          sudo -u testuser bash <<'EOF'
            set -euxo pipefail
            # 3) install.sh の実行（ファイル存在確認付き）
            if [ -f "$HOME/.config/bootstrap/install.sh" ]; then
              bash "$HOME/.config/bootstrap/install.sh"
            else
              echo "install.sh not found!" >&2
              exit 1
            fi
          EOF
